### ISSUE TITLE
Little Wing x64 version pour Windows

### ISSUE THREAD

**Issue by ChessGUI** [vinc/littlewing#2]
Salut,

Hermann Krause en Allemagne a fait un compilé ici: https://mega.nz/#F!z8lzwKRY!NNbIAN7pEX7J-jD_kPwdRA

**Comment by vinc** [comment]
Hi, it should be easier now that rust is more mature to cross compile for Windows from GNU/Linux. If it work I'll provide official binaries.

**Comment by vinc** [comment]
@ChessGUI I put some binaries for the old 0.2.0 version on my [website][1], would you mind checking the Windows 64bit version? The test suite pass through wine so it should be okay.

I'll need to publish a 0.3.0 version though, because the code changed a bit since then, but the engine is still very weak.

[1]: https://vinc.cc/bin/
