### ISSUE TITLE
Illegal castling move (v0.5)

### ISSUE THREAD

**Issue by rchastain** [vinc/littlewing#51]
Hello!

LittleWing 0.5 made an illegal castling move in the following game.

Happy new year!

Regards.

Roland
[littlewing05-bug01.zip](https://github.com/vinc/littlewing/files/4022985/littlewing05-bug01.zip)

**Comment by vinc** [comment]
Hi Roland, thanks for reporting the bug!

It should be fixed in Little Wing v0.6.0, released last month, with this commit: https://github.com/vinc/littlewing/commit/e9d3cc7f3a52c80dde171a1fc234c0538def2ad1

Until that commit if the kind moved, the castling rights were removed on the king side but not on the queen side, so if the king went back to it's original square it could still castle on the queen side!

https://vinc.cc/blog/2019/12/22/little-wing-0-6-0-released/
https://vinc.cc/binaries/littlewing-v0.6.0/

**Comment by rchastain** [comment]
Thank you for your answer. I hadn't seen that release. I will try it at once.

Regards.

Roland

**Comment by rchastain** [comment]
Wow, there are many improvements!

And, I have already said, but your website is beau-ti-ful. Congratulations.

LittleWing will be included in the next release of my chess GUI.

Regards.

Roland

**Comment by vinc** [comment]
Thanks Roland!

I'm excited to see Little Wing included in your chess GUI! I'm going to check it :)

**Comment by rchastain** [comment]
Hello Vincent!

The new release of Eschecs, including Little Wing, is available. Hope you will like it. :)

By the way, I compiled by myself a Win32 binary of Little Wing. Installing Rust was easy but I noticed that the *export* command doesn't seem to exist under Windows, so I compiled simply like this:

`cargo build --release --target=i686-pc-windows-msvc`

I had a doubt about "i686". I would have thought "i386". But the binary works, so I guess it was the good option.

The binary is much smaller than the one you provided (1,5 Mo versus 6 Mo), I don't know why. I hope I didn't break something.

Why do I compile for Win32? For a stupid reason. One of the libraries used by Eschecs has some little bugs when it is compiled for Win64.

Best regards.

Roland
